version: "1"

services:
  - name: Greeter Backend
    type: web
    runtime: image
    image:
      url: ghcr.io/suomarte/greeter:latest
    plan: starter
    region: frankfurt
    autoDeployTrigger: off
